### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by DoodledPunks-Ken** [0xApeToshi/ERC721-snapshot#1]
I keep getting this error:

bash-3.2$ python main.py
  File "main.py", line 59
    url = f"https://api.etherscan.io/api?module=contract&action=getabi&address={CONTRACT_ADDR}"
                                                                                              ^
SyntaxError: invalid syntax

**Comment by 0xApeToshi** [comment]
Hmh, what OS and Python version are you using? My best guess is that you forgot to put quotes around the `CONTRACT_ADDR `- otherwise it's not a string but a hex number.

**Comment by 0xApeToshi** [comment]
I figured out what the problem was. On Mac OS and Linux, you need to use `pip3` and `python3`, otherwise it uses `python2`.
